import os

HUGGINGFACE_TOKEN = os.environ.get('HUGGINGFACE_TOKEN')
DATA_FOLDER = os.environ.get('DATA_FOLDER')
DATA_FOLDER_TESTING = os.environ.get('DATA_FOLDER_TESTING')
RNASTRUCTURE_PATH = os.environ.get('RNASTRUCTURE_PATH')
RNASTRUCTURE_TEMP_FOLDER = os.environ.get('RNASTRUCTURE_TEMP_FOLDER')