name: Python CI
on:
  push:
    branches: all
  pull_request:
    branches: [ main ]
  release:
    types: [created]

jobs:
  docstring-tests:
    # test docstrings
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Install dependencies
      env:
        HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
        HUGGINGFACE_TOKEN_WRONG: ${{ secrets.HUGGINGFACE_TOKEN_NOISEAEVSBRFS }}
        DATA_FOLDER: ${{ secrets.DATA_FOLDER }}
        DATA_FOLDER_TESTING: ${{ secrets.DATA_FOLDER_TESTING }}
        RNASTRUCTURE_PATH: ${{ secrets.RNASTRUCTURE_PATH }}
        RNASTRUCTURE_TEMP_FOLDER: ${{ secrets.RNASTRUCTURE_TEMP_FOLDER }}
      run: |
        python -m pip install --upgrade pip
        pip install .
        python -m pytest -v --doctest-modules
        