name: Python Publish Workflow
on:
  workflow_call:

jobs:
  publish:
     # only publish on pushes to master if the version has changed
    uses: microsoft/action-python/.github/workflows/publish.yml@0.6.4
    secrets:
      PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      TEST_PYPI_PASSWORD: ${{ secrets.TEST_PYPI_PASSWORD  }}
      BASE_BRANCH: ${{ github.event.inputs.base_branch }}
