name: Docs


permissions:
  actions: write
  checks: write
  contents: write
  deployments: write
  id-token: write
  issues: write
  discussions: write
  packages: write
  pages: write
  pull-requests: write
  repository-projects: write
  security-events: write
  statuses: write


on:
  push:
    branches: [main] # branch to trigger deployment

jobs:
  Build-Docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install requirements
        run: |
          pip install -r requirements.txt
          export HUGGINGFACE_TOKEN=${{ secrets.HUGGINGFACE_TOKEN }}
          export DATA_FOLDER=${{ secrets.DATA_FOLDER }}
          export DATA_FOLDER_TESTING=${{ secrets.DATA_FOLDER_TESTING }}
          export RNASTRUCTURE_PATH=${{ secrets.RNASTRUCTURE_PATH }}
          export RNASTRUCTURE_TEMP_FOLDER=${{ secrets.RNASTRUCTURE_TEMP_FOLDER }}



      - name: Sphinx build
        run: |
          cd docs
          sphinx-build -b html -d _build/doctrees . _build/html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/_build/html
          force_orphan: true
